#!/usr/bin/expect -f
set timeout 600
set ip "157.180.65.227"
set user "root"
set password "Irifeg8$"

spawn scp -o StrictHostKeyChecking=no teleboard_deploy.tar.gz $user@$ip:/opt/teleboard/
expect {
  "password:" { send "$password\r"; exp_continue }
  eof
}

spawn ssh -o StrictHostKeyChecking=no $user@$ip "cd /opt/teleboard; tar -xzf teleboard_deploy.tar.gz; docker compose -f docker-compose.prod.yml up -d --build"
expect {
  "password:" { send "$password\r"; exp_continue }
  eof
}
